/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SimpleGradle;

public class App {
    public String getGreeting() { return "Hello World!"; }
    public int factorial(int n){
        int product_sum = 1;
        for(int i=n; i>0; i--){
            product_sum = product_sum * i;
        }
        return product_sum;
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        System.out.println(new App().factorial(1));
        System.out.println(new App().factorial(2));
        System.out.println(new App().factorial(3));
        System.out.println(new App().factorial(4));
        System.out.println(new App().factorial(5));
    }
}
